import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const source = (relativePath) =>
  readFileSync(new URL(`../${relativePath}`, import.meta.url), "utf8");

test("Tailwind and semantic theme have one CSS source", () => {
  const indexCss = source("src/index.css");
  const appCss = source("src/App.css");

  assert.equal((indexCss.match(/@import\s+["']tailwindcss["']/g) || []).length, 1);
  assert.equal((appCss.match(/@import\s+["']tailwindcss["']/g) || []).length, 0);
  assert.match(indexCss, /@theme\s*{/);
  assert.match(indexCss, /--color-brand:/);
  assert.match(indexCss, /--color-danger:/);
});

test("shared notice exposes assertive errors and polite pending or success states", () => {
  const notice = source("src/shared/ui/Notice.tsx");

  assert.match(notice, /isError \? "alert" : "status"/);
  assert.match(notice, /isError \? "assertive" : "polite"/);
  assert.match(notice, /aria-busy={pending \|\| undefined}/);
  assert.match(notice, /aria-atomic="true"/);
});

test("F2 dashboard editor and share slice has no native alerts and owns direction boundaries", () => {
  const paths = [
    "src/modules/presentations/editor/toolbar/EditorHeader.jsx",
    "src/modules/presentations/sharing/ShareDialog.jsx",
    "src/modules/presentations/dashboard/PresentationDashboard.jsx",
    "src/modules/presentations/editor/routes/EditorRoute.jsx",
    "src/modules/presentations/editor/inspector/QuestionInspector.jsx",
    "src/modules/presentations/editor/slide-list/SlideList.jsx",
  ];
  const combined = paths.map(source).join("\n");

  assert.doesNotMatch(combined, /(?:window\.)?alert\s*\(/);
  assert.match(source("src/modules/presentations/editor/toolbar/EditorHeader.jsx"), /dir="auto"/);
  assert.match(source("src/modules/presentations/sharing/ShareDialog.jsx"), /dir="ltr"/);
  assert.match(source("src/modules/presentations/dashboard/PresentationDashboard.jsx"), /dir="auto"/);
});

test("protected manager routes share one persistent shell and recoverable error boundary", () => {
  const app = source("src/App.jsx");
  const shell = source("src/app/layouts/ProtectedManagerShell.tsx");

  assert.match(app, /<Route element={<ProtectedManagerShell \/>}>/);
  assert.match(shell, /<Outlet \/>/);
  assert.match(shell, /ManagerRouteErrorBoundary/);
  assert.match(shell, /previousProps\.resetKey !== this\.props\.resetKey/);
  assert.match(shell, /fa\.managerShell\.routeErrorTitle/);
});

test("typed Persian catalog is consumed by manager dashboard editor and share", () => {
  const catalog = source("src/shared/i18n/fa.ts");

  assert.match(catalog, /export const fa =/);
  assert.match(catalog, /as const/);
  assert.match(source("src/modules/presentations/dashboard/PresentationDashboard.jsx"), /fa\.dashboard\.title/);
  assert.match(source("src/modules/presentations/editor/routes/EditorRoute.jsx"), /fa\.managerShell\.backToDashboard/);
  assert.match(source("src/modules/presentations/sharing/ShareDialog.jsx"), /fa\.share\.title/);
});

test("presentation transport types come from the checked-in OpenAPI output", () => {
  const service = source("src/modules/presentations/api/presentationRepository.ts");
  const liveTypes = source("src/live/types.ts");
  const generated = source("src/shared/api/generated/openapi.ts");

  assert.match(generated, /This file was auto-generated by openapi-typescript/);
  assert.match(service, /components\["schemas"\]\["Presentation"\]/);
  assert.match(service, /components\["schemas"\]\["Slide"\]/);
  assert.match(liveTypes, /components\["schemas"\]\["Presentation"\]/);
  assert.doesNotMatch(service, /interface PresentationDTO/);
  assert.doesNotMatch(service, /interface SlideDTO/);
});

test("F3 owns presentation UI and creates slides only after type selection", () => {
  const route = source("src/modules/presentations/editor/routes/EditorRoute.jsx");
  const addStart = route.indexOf("const addNewSlide");
  const deleteStart = route.indexOf("const deleteSlide", addStart);
  const addFlow = route.slice(addStart, deleteStart);

  assert.match(source("src/modules/presentations/dashboard/PresentationDashboard.jsx"), /\.\.\/api\/presentationRepository/);
  assert.match(source("src/modules/presentations/sharing/ShareDialog.jsx"), /\.\.\/api\/presentationRepository/);
  assert.match(route, /useEditorStatus/);
  assert.match(route, /isCreatingSlide/);
  assert.doesNotMatch(addFlow, /quizService\.createSlide/);
  assert.match(route, /await quizService\.createSlide\(quiz\.quiz_id, newSlideData, quiz\.revision\)/);
});
