# Generated by Django 5.2.7 on 2025-10-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='player',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='slide',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای'), ('text', 'تشریحی'), ('true_false', 'صحیح/غلط')], default='multiple_choice', max_length=20),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
