# Generated by Django 5.2.7 on 2025-10-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_player_unique_together_remove_player_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slide',
        ),
        migrations.CreateModel(
            name='PickAnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='office.quiz')),
            ],
            options={
                'db_table': 'quiz_pickanswerquestion',
            },
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='office.pickanswerquestion'),
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
