# Generated by Django 5.2.7 on 2025-10-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_remove_question_slide_pickanswerquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickanswerquestion',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='pickanswerquestion',
            unique_together={('quiz', 'order')},
        ),
    ]
