# Generated by Django 5.2.7 on 2025-10-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_pickanswerquestion_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='pickanswerquestion',
            unique_together=set(),
        ),
    ]
