# Generated by Django 5.2.7 on 2025-10-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_option_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'order')},
        ),
    ]
